development:
  :address: smtp.sendgrid.net
  :port: 25
  :authentication: plain
  :user_name: postmaster@gbeddow.com
  :password: corelsync
production:
  :address: smtp.sendgrid.net
  :port: 25
  :authentication: plain
  :user_name: postmaster@gbeddow.com
  :password: corelsync
test:
  :address: smtp.sendgrid.net
  :port: 25
  :authentication: plain
  :user_name: postmaster@gbeddow.com
  :password: corelsync
